demo1:
	python sumofsquares.py -r inline sumofsquares_input.txt

demo2:
	python sumofoddsquares.py -r inline sumofsquares_input.txt

demo3:
	python sumofoddsquares2.py -r inline sumofsquares_input.txt

demo4:
	python wordcount_top10.py -r inline ../L02/hamlet.txt

