demo1:
	python sumofsquares.py -r inline sumofsquares_input.txt

demo2:
	python sumofoddsquares.py -r inline sumofsquares_input.txt

demo3:
	python sumofoddsquares2.py -r inline sumofsquares_input.txt

demo4:
	python wordcount_top10.py -r inline ../L02/hamlet.txt

demo5:
	/bin/rm -f join_data/*~	#make sure no temp files present
	python join_demo.py -r inline join_data/